version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 