services:
  - type: web
    name: detoxify-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 
      - key: HUGGING_FACE_TOKEN
        sync: false
      - fromGroup: huggingface